apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbt-go-filler-deployment
  namespace: default
  labels:
    app: cbt-go-filler-deployment
spec:
  replicas: 15
  selector:
    matchLabels:
      app: cbt-go-filler-deployment
  template:
    metadata:
      labels:
        app: cbt-go-filler-deployment
    spec:
      serviceAccountName: kube-cbt-admin
      containers:
      - name: cbt-go-filler-deployment
        image: gcr.io/piotrostr-resources/cbt-go-filler
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi

---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cbt-go-filler-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       cbt-go-filler-deployment
  updatePolicy:
    updateMode: "Auto"
